#!/usr/bin/python3
"""
Build arreglos/tab-index.js — a lookup table of extracted tablatures
indexed by normalized song title.

Run after batch-extract.py:
  /usr/bin/python3 build-index.py

Then include <script src="arreglos/tab-index.js"></script> in index.html.
"""

import os
import glob
import re
import json

script_dir = os.path.dirname(os.path.abspath(__file__))
canciones_dir = os.path.join(script_dir, "canciones")
output_path = os.path.join(script_dir, "tab-index.js")

def normalize(name):
    """Normalize song name for matching: lowercase, remove bpm/parenthetical noise."""
    n = name.split("(")[0].split("[")[0].strip()
    n = re.sub(r'[^a-záéíóúñ\s]', '', n.lower()).strip()
    return n

index = {}
for txt_path in sorted(glob.glob(os.path.join(canciones_dir, "*.txt"))):
    basename = os.path.splitext(os.path.basename(txt_path))[0]
    key = normalize(basename)
    with open(txt_path, "r") as f:
        text = f.read()
    if text.strip():
        index[key] = text

with open(output_path, "w") as f:
    f.write("// Auto-generated by build-index.py\n")
    f.write("// Maps normalized song titles to extracted tablature text.\n")
    f.write("const TAB_INDEX = ")
    json.dump(index, f, ensure_ascii=False, indent=1)
    f.write(";\n")

print(f"tab-index.js built: {len(index)} entries → {output_path}")
